import { recommendationValidationWalletStates as states } from "../fixtures/wallet-states/states";
import { hydratedScenario } from "./scenarioHelpers";

export const rotatingCategoryScenarios = [
  hydratedScenario({
    id: "rotating-active-001",
    name: "Activated rotating category wins in quarter",
    tags: ["curated", "rotating", "activation"],
    wallet: ["chase-freedom-flex", "capital-one-venture"],
    merchantName: "Shell",
    category: "gas",
    amount: 100,
    walletBenefitStates: [states.freedomGasActivated],
    expectedRuleType: "category",
  }),
  hydratedScenario({
    id: "rotating-not-activated-001",
    name: "Unactivated rotating category cannot win",
    tags: ["curated", "rotating", "activation"],
    wallet: ["chase-freedom-flex", "capital-one-venture"],
    merchantName: "Shell",
    category: "gas",
    amount: 100,
    walletBenefitStates: [states.freedomGasNotActivated],
    expectedRuleType: "base",
  }),
  hydratedScenario({
    id: "rotating-cap-exhausted-001",
    name: "Exhausted rotating category cannot win",
    tags: ["curated", "rotating", "cap"],
    wallet: ["chase-freedom-flex", "capital-one-venture"],
    merchantName: "Shell",
    category: "gas",
    amount: 100,
    walletBenefitStates: [states.freedomGasCapExhausted],
    expectedRuleType: "base",
  }),
  hydratedScenario({
    id: "rotating-before-effective-001",
    name: "One millisecond before quarter start is not effective",
    tags: ["curated", "rotating", "date"],
    wallet: ["chase-freedom-flex", "capital-one-venture"],
    merchantName: "Shell",
    category: "gas",
    amount: 100,
    transactionDate: "2026-06-30T23:59:59.999Z",
    walletBenefitStates: [states.freedomGasActivated],
    expectedRuleType: "base",
  }),
  hydratedScenario({
    id: "rotating-quarter-start-001",
    name: "Quarter start boundary",
    tags: ["curated", "rotating", "date"],
    wallet: ["chase-freedom-flex", "capital-one-venture"],
    merchantName: "Shell",
    category: "gas",
    amount: 100,
    transactionDate: "2026-07-01T00:00:00.000Z",
    walletBenefitStates: [states.freedomGasActivated],
    expectedRuleType: "category",
  }),
  hydratedScenario({
    id: "rotating-before-expiration-001",
    name: "One millisecond before quarter expiration remains active",
    tags: ["curated", "rotating", "date"],
    wallet: ["chase-freedom-flex", "capital-one-venture"],
    merchantName: "Shell",
    category: "gas",
    amount: 100,
    transactionDate: "2026-09-30T23:59:58.999Z",
    walletBenefitStates: [states.freedomGasActivated],
    expectedRuleType: "category",
  }),
  hydratedScenario({
    id: "rotating-quarter-end-001",
    name: "Quarter end boundary",
    tags: ["curated", "rotating", "date"],
    wallet: ["chase-freedom-flex", "capital-one-venture"],
    merchantName: "Shell",
    category: "gas",
    amount: 100,
    transactionDate: "2026-09-30T23:59:59.000Z",
    walletBenefitStates: [states.freedomGasActivated],
    expectedRuleType: "category",
  }),
  hydratedScenario({
    id: "rotating-after-quarter-001",
    name: "After quarter expiration falls back",
    tags: ["curated", "rotating", "date"],
    wallet: ["chase-freedom-flex", "capital-one-venture"],
    merchantName: "Shell",
    category: "gas",
    amount: 100,
    transactionDate: "2026-10-01T00:00:01.000Z",
    walletBenefitStates: [states.freedomGasActivated],
    expectedRuleType: "base",
  }),
];
