import { recommendationValidationWalletStates as states } from "../fixtures/wallet-states/states";
import { hydratedScenario } from "./scenarioHelpers";

export const statementCreditScenarios = [
  hydratedScenario({
    id: "statement-credit-full-001",
    name: "Full statement credit remaining",
    tags: ["curated", "statement-credit"],
    wallet: ["bestbuy-offer-card", "capital-one-venture"],
    merchantName: "Best Buy",
    category: "general_retail",
    amount: 120,
    walletBenefitStates: [states.bestBuyCreditRemaining],
    expectedRuleType: "statement_credit",
  }),
  hydratedScenario({
    id: "statement-credit-partial-001",
    name: "Partial statement credit remaining",
    tags: ["curated", "statement-credit", "credit"],
    wallet: ["bestbuy-offer-card", "capital-one-venture"],
    merchantName: "Best Buy",
    category: "general_retail",
    amount: 120,
    walletBenefitStates: [states.bestBuyCreditPartial],
    expectedRuleType: "statement_credit",
  }),
  hydratedScenario({
    id: "statement-credit-small-purchase-001",
    name: "Statement credit cannot exceed purchase amount",
    tags: ["curated", "statement-credit", "credit"],
    wallet: ["bestbuy-offer-card", "capital-one-venture"],
    merchantName: "Best Buy",
    category: "general_retail",
    amount: 5,
    walletBenefitStates: [states.bestBuyCreditRemaining],
    expectedRuleType: "statement_credit",
  }),
  hydratedScenario({
    id: "statement-credit-exhausted-001",
    name: "Exhausted statement credit cannot win",
    tags: ["curated", "statement-credit", "credit"],
    wallet: ["bestbuy-offer-card", "capital-one-venture"],
    merchantName: "Best Buy",
    category: "general_retail",
    amount: 120,
    walletBenefitStates: [states.bestBuyCreditExhausted],
    expectedRuleType: "base",
  }),
  hydratedScenario({
    id: "statement-credit-not-enrolled-001",
    name: "Statement credit cannot win before enrollment",
    tags: ["curated", "statement-credit", "enrollment"],
    wallet: ["bestbuy-offer-card", "capital-one-venture"],
    merchantName: "Best Buy",
    category: "general_retail",
    amount: 120,
    walletBenefitStates: [states.bestBuyCreditNotEnrolled],
    expectedRuleType: "base",
  }),
];
