export type {
  CheckoutProvider,
  CommerceModel,
  MarketplaceContext,
  MerchantCandidate,
  MerchantClassification,
  MerchantConfidenceBand,
  MerchantContext,
  MerchantDomSignal,
  MerchantEvidence,
  MerchantEvidenceType,
  MerchantIdentity,
  MerchantIntelligenceInput,
  MerchantIntelligenceResult,
  MerchantIntelligenceTrace,
  MerchantPurchaseChannel,
  MerchantResolutionStatus,
  StructuredMerchantSignal,
} from "../merchantIntelligenceService";
